#include "zscript/items/doom.zsc"
#include "zscript/items/chexquest.zsc"
#include "zscript/items/heretic.zsc"
#include "zscript/items/hexen.zsc"
#include "zscript/items/strife.zsc"

class BlueBastardHealthBonus : HealthBonus
{
	override bool TryPickup (in out Actor other)
	{
		PrevHealth = other.player != NULL ? other.player.health : other.health;
		
		int blehhh = 200;
		if (other.FindInventory("SpotMallet"))
		{
			blehhh += 50;
		}
		if (other.GiveBody(Amount, blehhh))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}

class BlueBastardsBerserk : CustomInventory Replaces Berserk {
	Default
	{
		+COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.ISHEALTH
		Inventory.PickupMessage "$GOTBERSERK";
		Inventory.PickupSound "misc/berserk";
	}

	override bool TryPickup (in out Actor toucher)
	{
		let pickupstate = FindState('Pickup');
		bool useok = CallStateChain (toucher, pickupstate);

		if ((useok || pickupstate == NULL) && FindState('Use') != NULL)
		{
			useok = Super.TryPickup (toucher);
		}

		if (useok) {
			if (allow_spot_dragon) {
				if (toucher.FindInventory("SpotMallet"))
				{
					toucher.A_GiveInventory("Dragon_Spot_Transform");
					let [k1, k2] = Bindings.GetKeysForCommand("+reload");
					string s1 = Bindings.NameKeys(k1, k2);
					string tip = String.Format(StringTable.Localize("$SPOT_TRANSFORM_TIP"), s1);
					toucher.A_Print(tip);
				}
				if (toucher.FindInventory("DeathsheadFist"))
				{
					toucher.A_GiveInventory("Mothman_Transform");
					let [k1, k2] = Bindings.GetKeysForCommand("+reload");
					string s1 = Bindings.NameKeys(k1, k2);
					string tip = String.Format(StringTable.Localize("$ACE_TRANSFORM_TIP"), s1);
					toucher.A_Print(tip);
				}
			}
			GoAwayAndDie();
		}
		return useok;
	}

	States
	{
	Spawn:
		PSTR A -1 Bright;
		Stop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PowerStrength");
		TNT1 A 0 HealThing(100, 0);
		TNT1 A 0 A_SelectWeapon("SpotMallet");
		TNT1 A 0 A_SelectWeapon("DeathsheadFist");
		Stop;
	}
}

class BlueBastardsTransformationFog : Actor
{
	default
	{
		+NOBLOCKMAP
		+NOTELEPORT
		+NOGRAVITY
		+ZDOOMTRANS
		RenderStyle "Add";
	}
	States
	{
	Spawn:
		TFOG ABABCDEFGHIJ 2 Bright;
		Stop;
	}
	override void PostBeginPlay ()
	{
		Super.PostBeginPlay ();
		A_StartSound ("misc/transformation", CHAN_BODY);
	}
}

class HalfPigInABlanket : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTLASTBLANKET";
	}
	States
	{
	Spawn:
		PBNK A -1;
		Loop;
	}
}

class HalfBurger : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTHALFBURGER";
	}
	States
	{
	Spawn:
		BURG A -1;
		Loop;
	}
}

class MreBiscuit : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTLASTMREBISCUIT";
	}
	States
	{
	Spawn:
		BSCT A -1;
		Loop;
	}
}

class ChipCrumb : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTCRUMBS";
	}
	States
	{
	Spawn:
		CHIP A -1;
		Loop;
	}
}

class DrGibbCan : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/can_open";
		Inventory.PickupMessage "$GOTDRGIBB";
	}
	States
	{
	Spawn:
		GIBB A -1;
		Loop;
	}
}

class DrGibbGlass : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/drink";
		Inventory.PickupMessage "$GOTGLASSDRGIBB";
	}
	States
	{
	Spawn:
		GIBB C -1;
		Loop;
	}
}

class WhiskeyGlass : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/drink";
		Inventory.PickupMessage "$GOTGLASSWHISKEY";
	}
	States
	{
	Spawn:
		GIBB D -1;
		Loop;
	}
}

class WhiskeyBottle : Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/bottle_open";
		Inventory.PickupMessage "$GOTWHISKEY";
	}
	States
	{
	Spawn:
		GIBB B -1;
		Loop;
	}
}

class VodkaBottle : Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/bottle_open";
		Inventory.PickupMessage "$GOTVODKA";
	}
	States
	{
	Spawn:
		IVDK A -1;
		Loop;
	}
}

class MysteryCan : Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/can_open";
		Inventory.PickupMessage "$GOTMCAN";
	}
	States
	{
	Spawn:
		MCAN A -1;
		Loop;
	}
}

class ChickenHeal : Medikit
{
	Default
	{
		Inventory.PickupSound "misc/gulp";
		Inventory.PickupMessage "$GOTCHICKEN";
	}
	States
	{
	Spawn:
		CHIK ABCDEF 3;
		Loop;
	}
}

class Medkit_Mslug : Medikit
{
	States
	{
	Spawn:
		MDKT A -1;
		Loop;
	}
}
//Ammo distribution base
class BBAmmoDistributor : Custominventory
{

	Action int A_ammomultiplier(int amount)
	{
		if(bdropped) return amount/2;
		return amount;
	}
	Action bool A_AllowedToGrab(class<Ammo> ammotype)
	{
		if(self.player.mo && self.player.mo.health>0)
		{
			
			if((self.player.mo.CountInv(ammotype)) == (GetAmmoCapacity(ammotype))) { return false; }
			else return true;
		}
		else return false;
	}
	
	states
	{
	Cantpickup:
		TNT1 A 1;
		fail;
	}
}