//Removing the replaces parts as they do not do anything here, might also recommend just add a prefix to the class name to prevent issues, like BB or BlueBastard.
class Spot : DoomPlayer
{
	Default
	{
		Health 125;
		Player.DisplayName "$PLAYER_SPOT";
		Player.SoundClass "spot";
		Player.ScoreIcon "FACESPOT";
		Player.Face "SPT";
		Player.ColorRange 192, 207;
		Player.CrouchSprite "SPCR";
		Player.Colorset 0, "$TXT_COLOR_LIGHTBLUE",	0xC0, 0xCF,  0xC2;
		Player.Colorset 7, "$TXT_COLOR_GREEN",		0x70, 0x7F,  0x72;
		Player.Portrait "PRT_SPOT";

		//Player.StartItem "Dragon_Spot_Transform";
		Player.StartItem "SpotLevelEnter";
		Player.StartItem "SpotMallet";
		Player.StartItem "SpotExpress600";
		Player.StartItem "SpotKicky";
		Player.StartItem "BBSpot600", 12;
		
		Player.WeaponSlot 1, "SpotMallet", "SpotChainsaw";
		Player.WeaponSlot 2, "SpotExpress600";
		Player.WeaponSlot 3, "SpotShotgun", "SpotShotgunClassic", "SpotDevastator";
		Player.WeaponSlot 4, "SpotChaingun", "SpotM249";
		Player.WeaponSlot 5, "SpotRocketLauncher";
		Player.WeaponSlot 6, "SpotPlasmaRifle";
		Player.WeaponSlot 7, "SpotBFG";
		
		Player.MaxHealth 125;
		Speed 0.9;
	}
	override void PostBeginPlay(){
		Super.PostBeginPlay();
		{
			if (GetCVar("use_spot_alt_voice")) {
				let pp = PlayerPawn(self);
				if (pp)
				{
					pp.SoundClass = "spotalt";
				}
			}
		}
	}
	States
	{
	Spawn:
		SPOT A -1;
		Loop;
	See:
		SPOT ABCD 4;
		Loop;
	Missile:
		SPOT E 12;
		Goto Spawn;
	Melee:
		SPOT F 6 BRIGHT;
		Goto Missile;
	Pain:
		SPOT G 4;
		SPOT G 4 A_Pain;
		Goto Spawn;
	Death:
		SPOT H 0 A_PlayerSkinCheck("AltSkinDeath");
	Death1:
		SPOT H 10;
		SPOT I 10 A_PlayerScream;
		SPOT J 10 A_NoBlocking;
		SPOT KLM 10;
		SPOT N -1;
		Stop;
	XDeath:
		SPOT O 0 A_PlayerSkinCheck("AltSkinXDeath");
	XDeath1:
		SPOT O 5;
		SPOT P 5 A_XScream;
		SPOT Q 5 A_NoBlocking;
		SPOT RSTUV 5;
		SPOT W -1;
		Stop;
	AltSkinDeath:
		SPOT H 6;
		SPOT I 6 A_PlayerScream;
		SPOT JK 6;
		SPOT L 6 A_NoBlocking;
		SPOT MNO 6;
		SPOT P -1;
		Stop;
	AltSkinXDeath:
		SPOT Q 5 A_PlayerScream;
		SPOT R 0 A_NoBlocking;
		SPOT R 5 A_SkullPop;
		SPOT STUVWX 5;
		SPOT Y -1;
		Stop;
	}
}

class SpotDragon : Spot
{
	Default
	{
		Player.WeaponSlot 1, "BBSpot_Dragon_Claws";
		Player.MorphWeapon "BBSpot_Dragon_Claws";
		Player.Face "DRG";
		Speed 1.1;
		Player.ViewBob 0.5;
		Player.ViewBobSpeed 1.07;
		+INVULNERABLE;
	}

	// Bobbing when the player is transformed won't work otherwise unless i override this entire function.
	// Taken from Playerpawn with modifiactions.
	override void CalcHeight()
	{
		let player = self.player;
		double angle;
		double bob;
		bool still = false;

		// 

		if (player.cheats & CF_NOCLIP2)
		{
			player.bob = 0;
		}
		else if (bNoGravity && !player.onground)
		{
			player.bob = min(abs(0.5 * FlyBob), MAXBOB);
		}
		else
		{
			player.bob = player.Vel dot player.Vel;
			if (player.bob == 0)
			{
				still = true;
			}
			else
			{
				player.bob *= player.GetMoveBob();

				if (player.bob > MAXBOB)
					player.bob = MAXBOB;
			}
		}

		double defaultviewheight = ViewHeight + player.crouchviewdelta;

		if (player.cheats & CF_NOVELOCITY)
		{
			player.viewz = pos.Z + defaultviewheight;

			if (player.viewz > ceilingz-4)
				player.viewz = ceilingz-4;

			return;
		}

		if (bFly && !GetCVar("FViewBob"))
		{
			bob = 0;
		}
		else if (still)
		{
			if (player.health > 0)
			{
				angle = player.BobTimer / (120 * TICRATE / 35.) * 360.;
				bob = player.GetStillBob() * sin(angle);
			}
			else
			{
				bob = 0;
			}
		}
		else
		{
			angle = player.BobTimer / (ViewBobSpeed * TICRATE / 35.) * 360.;
			bob = player.bob * sin(angle) * (waterlevel > 1 ? 0.25f : 0.5f);
		}

		// move viewheight
		if (player.playerstate == PST_LIVE)
		{
			player.viewheight += player.deltaviewheight;

			if (player.viewheight > defaultviewheight)
			{
				player.viewheight = defaultviewheight;
				player.deltaviewheight = 0;
			}
			else if (player.viewheight < (defaultviewheight/2))
			{
				player.viewheight = defaultviewheight/2;
				if (player.deltaviewheight <= 0)
					player.deltaviewheight = 1 / 65536.;
			}

			if (player.deltaviewheight)
			{
				player.deltaviewheight += 0.25;
				if (!player.deltaviewheight)
					player.deltaviewheight = 1/65536.;
			}
		}

		//if (Alternative)
		//{
		//	bob = 0;
		//}
		player.viewz = pos.Z + player.viewheight + (bob * clamp(ViewBob, 0. , 1.5)); // [SP] Allow DECORATE changes to view bobbing speed.

		if (Floorclip && player.playerstate != PST_DEAD
			&& pos.Z <= floorz)
		{
			player.viewz -= Floorclip;
		}
		if (player.viewz > ceilingz - 4)
		{
			player.viewz = ceilingz - 4;
		}
		if (player.viewz < floorz + 4)
		{
			player.viewz = floorz + 4;
		}
	}
}

class Deathshead : DoomPlayer replaces DoomPlayer
{
	Default
	{
		Player.CrouchSprite "MOFC";
		Player.DisplayName "$PLAYER_DEATHSHEAD";
		Player.SoundClass "deathshead";
		Player.ScoreIcon "FACEACE";
		Player.Face "MOF";
		Player.DamageScreenColor "37732b";
		Player.ColorRange 192, 207;
		Player.Colorset 0, "$TXT_COLOR_BLUE", 0xC2, 0xCB,  0xCF;
		Player.Portrait "PRT_ACE";
		BloodColor "37732b";
		
		Player.StartItem "DeathsheadLevelEnter";
		Player.StartItem "DeathsheadFist";
		Player.StartItem "DeathsheadKicky";
		Player.StartItem "DeathsheadPistol";
		Player.StartItem "BBDeathshead9mm", 50;
		
		Player.WeaponSlot 1, "DeathsheadFist", "DeathsheadChainsaw";
		Player.WeaponSlot 2, "DeathsheadPistol", "DeathsheadMAC10";
		Player.WeaponSlot 3, "DeathsheadShotgun", "DeathsheadSuperShotgun";
		Player.WeaponSlot 4, "DeathsheadSG550", "DeathsheadM4";
		Player.WeaponSlot 5, "DeathsheadRocketLauncher";
		Player.WeaponSlot 6, "DeathsheadPlasmaRifle";
		Player.WeaponSlot 7, "DeathsheadBFG";
	}
	States
	{
	Spawn:
		MOFF A -1;
		Loop;
	See:
		MOFF ABCD 4;
		Loop;
	Missile:
		MOFF E 12;
		Goto Spawn;
	Melee:
		MOFF F 6 BRIGHT;
		Goto Missile;
	Pain:
		MOFF G 4;
		MOFF G 4 A_Pain;
		Goto Spawn;
	Death:
		MOFF H 0 A_PlayerSkinCheck("AltSkinDeath");
	Death1:
		MOFF H 10;
		MOFF I 10 A_PlayerScream;
		MOFF J 10 A_NoBlocking;
		MOFF KLM 10;
		MOFF N -1;
		Stop;
	XDeath:
		MOFF O 0 A_PlayerSkinCheck("AltSkinXDeath");
	XDeath1:
		MOFF O 5;
		MOFF P 5 A_XScream;
		MOFF Q 5 A_NoBlocking;
		MOFF RSTUV 5;
		MOFF W -1;
		Stop;
	AltSkinDeath:
		MOFF H 6;
		MOFF I 6 A_PlayerScream;
		MOFF JK 6;
		MOFF L 6 A_NoBlocking;
		MOFF MNO 6;
		MOFF P -1;
		Stop;
	AltSkinXDeath:
		MOFF Q 5 A_PlayerScream;
		MOFF R 0 A_NoBlocking;
		MOFF R 5 A_SkullPop;
		MOFF STUVWX 5;
		MOFF Y -1;
		Stop;
	}
}

class DeathsheadMothman : Deathshead
{
	Default
	{
		Player.WeaponSlot 1, "MothmanWhiskeyBottle";
		Player.MorphWeapon "MothmanWhiskeyBottle";
		Speed 1.1;
		Player.Face "MFM";
		+INVULNERABLE;
	}
	
	override void CalcHeight()
	{
		let player = self.player;
		double angle;
		double bob;
		bool still = false;

		// 

		if (player.cheats & CF_NOCLIP2)
		{
			player.bob = 0;
		}
		else if (bNoGravity && !player.onground)
		{
			player.bob = min(abs(0.5 * FlyBob), MAXBOB);
		}
		else
		{
			player.bob = player.Vel dot player.Vel;
			if (player.bob == 0)
			{
				still = true;
			}
			else
			{
				player.bob *= player.GetMoveBob();

				if (player.bob > MAXBOB)
					player.bob = MAXBOB;
			}
		}

		double defaultviewheight = ViewHeight + player.crouchviewdelta;

		if (player.cheats & CF_NOVELOCITY)
		{
			player.viewz = pos.Z + defaultviewheight;

			if (player.viewz > ceilingz-4)
				player.viewz = ceilingz-4;

			return;
		}

		if (bFly && !GetCVar("FViewBob"))
		{
			bob = 0;
		}
		else if (still)
		{
			if (player.health > 0)
			{
				angle = player.BobTimer / (120 * TICRATE / 35.) * 360.;
				bob = player.GetStillBob() * sin(angle);
			}
			else
			{
				bob = 0;
			}
		}
		else
		{
			angle = player.BobTimer / (ViewBobSpeed * TICRATE / 35.) * 360.;
			bob = player.bob * sin(angle) * (waterlevel > 1 ? 0.25f : 0.5f);
		}

		// move viewheight
		if (player.playerstate == PST_LIVE)
		{
			player.viewheight += player.deltaviewheight;

			if (player.viewheight > defaultviewheight)
			{
				player.viewheight = defaultviewheight;
				player.deltaviewheight = 0;
			}
			else if (player.viewheight < (defaultviewheight/2))
			{
				player.viewheight = defaultviewheight/2;
				if (player.deltaviewheight <= 0)
					player.deltaviewheight = 1 / 65536.;
			}

			if (player.deltaviewheight)
			{
				player.deltaviewheight += 0.25;
				if (!player.deltaviewheight)
					player.deltaviewheight = 1/65536.;
			}
		}

		//if (Alternative)
		//{
		//	bob = 0;
		//}
		player.viewz = pos.Z + player.viewheight + (bob * clamp(ViewBob, 0. , 1.5)); // [SP] Allow DECORATE changes to view bobbing speed.

		if (Floorclip && player.playerstate != PST_DEAD
			&& pos.Z <= floorz)
		{
			player.viewz -= Floorclip;
		}
		if (player.viewz > ceilingz - 4)
		{
			player.viewz = ceilingz - 4;
		}
		if (player.viewz < floorz + 4)
		{
			player.viewz = floorz + 4;
		}
	}
}