// so it doesn't draw the weapons (bueghhhh graphics missing)
class BlueBastardsAltHud : AltHud
{
	override void DrawOneWeapon(PlayerInfo CPlayer, int x, in out int y, Weapon weapon)
	{
	}
	override void DrawWeapons(PlayerInfo CPlayer, int x, int y)
	{
	}
}

class BlueBastardsStatusBar : BaseStatusBar
{
	DynamicValueInterpolator mHealthInterpolator;
	DynamicValueInterpolator mArmorInterpolator;
	
	//Taken from Doomstatusbar
	HUDFont mHUDFont;
	HUDFont mIndexFont;
	HUDFont mAmountFont;
	InventoryBarState diparms;
	
	protected virtual void DrawBarKeys()
	{
		bool locks[6];
		String image;
		for(int i = 0; i < 6; i++) locks[i] = CPlayer.mo.CheckKeys(i + 1, false, true);
		// key 1
		if (locks[1] && locks[4]) image = "STKEYS6";
		else if (locks[1]) image = "STKEYS0";
		else if (locks[4]) image = "STKEYS3";
		DrawImage(image, (239, 171), DI_ITEM_OFFSETS);
		// key 2
		if (locks[2] && locks[5]) image = "STKEYS7";
		else if (locks[2]) image = "STKEYS1";
		else if (locks[5]) image = "STKEYS4";
		else image = "";
		DrawImage(image, (239, 181), DI_ITEM_OFFSETS);
		// key 3
		if (locks[0] && locks[3]) image = "STKEYS8";
		else if (locks[0]) image = "STKEYS2";
		else if (locks[3]) image = "STKEYS5";
		else image = "";
		DrawImage(image, (239, 191), DI_ITEM_OFFSETS);
	}

	protected virtual void DrawBarAmmo()
	{
		int amt1, maxamt;
		let pPawn = doomplayer(CPlayer.mo);
		
		if(pPawn) 
		{
			if(pPawn is 'Spot')
			{
				if(pPawn.Player.ReadyWeapon.GetClassName() == "SpotChaingun")
				{
					[amt1, maxamt] = GetAmount("BBSpotNavalBullets");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 173), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 173), DI_TEXT_ALIGN_RIGHT);
				}else
				if(pPawn.Player.ReadyWeapon.GetClassName() ==  "SpotExpress600")
				{
					[amt1, maxamt] = GetAmount("BBSpot600");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 173), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 173), DI_TEXT_ALIGN_RIGHT);
				}
				else
				{
					[amt1, maxamt] = GetAmount("Clip");
					DrawString(mIndexFont, FormatNumber(amt1, 2), (288, 173), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 2), (314, 173), DI_TEXT_ALIGN_RIGHT);
				}
				if(pPawn.Player.ReadyWeapon.GetClassName() !=  "SpotDevastator")
				{
					[amt1, maxamt] = GetAmount("BBSpotDevastatorShell");
					DrawString(mIndexFont, FormatNumber(amt1, 2), (288, 179), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 2), (314, 179), DI_TEXT_ALIGN_RIGHT);
				}
				else
				{
					[amt1, maxamt] = GetAmount("Shell");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 179), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 179), DI_TEXT_ALIGN_RIGHT);
				}
				[amt1, maxamt] = GetAmount("RocketAmmo");
				DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 185), DI_TEXT_ALIGN_RIGHT);
				DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 185), DI_TEXT_ALIGN_RIGHT);
				if(pPawn.Player.ReadyWeapon.GetClassName() ==  "SpotBFG")
				{
					[amt1, maxamt] = GetAmount("BBSpotAtomicBomb");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 191), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 191), DI_TEXT_ALIGN_RIGHT);
					DrawImage("graphics/stbar_nuke.png", (249, 168), DI_ITEM_OFFSETS);
				}
				else
				{
					[amt1, maxamt] = GetAmount("Cell");
					DrawString(mIndexFont, FormatNumber(amt1, 2), (288, 191), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 2), (314, 191), DI_TEXT_ALIGN_RIGHT);
				}
			}
			if(pPawn is 'Deathshead')
			{
				if(pPawn.Player.ReadyWeapon.GetClassName() == "DeathsheadMAC10" || pPawn.Player.ReadyWeapon.GetClassName() ==  "DeathsheadPistol")
				{
					[amt1, maxamt] = GetAmount("BBDeathshead9mm");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 173), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 173), DI_TEXT_ALIGN_RIGHT);
					DrawImage("graphics/stbar_9mm.png", (249, 168), DI_ITEM_OFFSETS);
				}
				else
				{
					[amt1, maxamt] = GetAmount("BBDeathshead556");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 173), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 173), DI_TEXT_ALIGN_RIGHT);
				}
				[amt1, maxamt] = GetAmount("Shell");
				DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 179), DI_TEXT_ALIGN_RIGHT);
				DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 179), DI_TEXT_ALIGN_RIGHT);
				if(pPawn.Player.ReadyWeapon.GetClassName() != "DeathsheadM4")
				{
					[amt1, maxamt] = GetAmount("RocketAmmo");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 185), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 185), DI_TEXT_ALIGN_RIGHT);
				}
				else
				{
					[amt1, maxamt] = GetAmount("BBDeathsheadGrenade");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 185), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 2), (314, 185), DI_TEXT_ALIGN_RIGHT);
					DrawImage("graphics/stbar_gren.png", (249, 168), DI_ITEM_OFFSETS);
				}
				if(pPawn.Player.ReadyWeapon.GetClassName() != "DeathsheadBFG")
				{
					[amt1, maxamt] = GetAmount("Cell");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 191), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 3), (314, 191), DI_TEXT_ALIGN_RIGHT);
				}
				else
				{
					[amt1, maxamt] = GetAmount("BBDeathsheadBFGCell");
					DrawString(mIndexFont, FormatNumber(amt1, 3), (288, 191), DI_TEXT_ALIGN_RIGHT);
					DrawString(mIndexFont, FormatNumber(maxamt, 2), (314, 191), DI_TEXT_ALIGN_RIGHT);
				}
			}
		}
	}
	
	
	override void Init()
	{
		Super.Init();
		SetSize(32, 320, 200);
		Font fnt = "HUDFONT_DOOM";
		mHUDFont = HUDFont.Create(fnt, fnt.GetCharWidth("0"), Mono_CellLeft, 1, 1);
		fnt = "INDEXFONT_DOOM";
		mIndexFont = HUDFont.Create(fnt, fnt.GetCharWidth("0"), Mono_CellLeft);
		mAmountFont = HUDFont.Create("INDEXFONT");
		diparms = InventoryBarState.Create();
		mHealthInterpolator = DynamicValueInterpolator.Create(0, 0.5, 1, 16);
		mArmorInterpolator = DynamicValueInterpolator.Create(0, 0.5, 1, 24);
	}
	override void NewGame ()
	{
		Super.NewGame();
		mHealthInterpolator.Reset (0);
		mArmorInterpolator.Reset (0);
	}
	override void Tick()
	{
		Super.Tick();
		mHealthInterpolator.Update(CPlayer.health);
		mArmorInterpolator.Update(GetArmorAmount());
	}
	
	override void Draw (int state, double TicFrac)
	{

		Super.Draw (state, TicFrac);
		
		if (state == HUD_StatusBar)
		{
			BeginStatusBar();
			DrawMainBullshit (TicFrac);
		}
		else if (state == HUD_Fullscreen)
		{
			BeginHUD();
			DrawFullScreenBullshit ();
		}
	}

	protected void DrawMainBullshit (double TicFrac)
	{
		DrawImage("STBAR", (0, 168), DI_ITEM_OFFSETS);
		DrawImage("STTPRCNT", (90, 171), DI_ITEM_OFFSETS);
		DrawImage("STTPRCNT", (221, 171), DI_ITEM_OFFSETS);

		Inventory a1 = GetCurrentAmmo();
		if (a1 != null) DrawString(mHUDFont, FormatNumber(a1.Amount, 3), (44, 171), DI_TEXT_ALIGN_RIGHT|DI_NOSHADOW);
		DrawString(mHUDFont, FormatNumber(mHealthInterpolator.GetValue(), 3), (90, 171), DI_TEXT_ALIGN_RIGHT|DI_NOSHADOW);
		DrawString(mHUDFont, FormatNumber(mArmorInterpolator.GetValue(), 3), (221, 171), DI_TEXT_ALIGN_RIGHT|DI_NOSHADOW);

		DrawBarKeys();
		DrawBarAmmo();

		if (deathmatch || teamplay)
		{
			DrawString(mHUDFont, FormatNumber(CPlayer.FragCount, 3), (138, 171), DI_TEXT_ALIGN_RIGHT);
		}
		else
		{
			BBDrawBarWeapons();
		}

		if (CPlayer.mo.InvSel != null && !Level.NoInventoryBar)
		{
			DrawInventoryIcon(CPlayer.mo.InvSel, (160, 198), DI_DIMDEPLETED);
			if (CPlayer.mo.InvSel.Amount > 1)
			{
				DrawString(mAmountFont, FormatNumber(CPlayer.mo.InvSel.Amount), (175, 198-mIndexFont.mFont.GetHeight()), DI_TEXT_ALIGN_RIGHT, Font.CR_GOLD);
			}
		}
		else
		{
			DrawTexture(GetMugShot(5,Mugshot.XDEATHFACE), (143, 168), DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		}
		if (isInventoryBarVisible())
		{
			DrawInventoryBar(diparms, (48, 169), 7, DI_ITEM_LEFT_TOP);
		}
	}

	void BBDrawBarWeapons()
	{
		DrawImage("STARMS", (104, 168), DI_ITEM_OFFSETS);
		DrawImage(CPlayer.HasWeaponsInSlot(2)? "STYSNUM2" : "STGNUM2", (110, 172), DI_ITEM_OFFSETS);
		DrawImage(CPlayer.HasWeaponsInSlot(3)? "STYSNUM3" : "STGNUM3", (122, 172), DI_ITEM_OFFSETS);
		DrawImage(CPlayer.HasWeaponsInSlot(4)? "STYSNUM4" : "STGNUM4", (134, 172), DI_ITEM_OFFSETS);
		DrawImage(CPlayer.HasWeaponsInSlot(5)? "STYSNUM5" : "STGNUM5", (110, 182), DI_ITEM_OFFSETS);
		DrawImage(CPlayer.HasWeaponsInSlot(6)? "STYSNUM6" : "STGNUM6", (122, 182), DI_ITEM_OFFSETS);
		DrawImage(CPlayer.HasWeaponsInSlot(7)? "STYSNUM7" : "STGNUM7", (134, 182), DI_ITEM_OFFSETS);
	}
	
	protected void DrawFullScreenBullshit ()
	{
		Vector2 iconbox = (40, 20);
		DrawImage("graphics/hud_mugshot.png", (4,-36), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		bool drawthatshit = false;
		// it's a fuckin' mess
		if (CPlayer.mo.FindInventory("PowerStrength")||CPlayer.mo.FindInventory("PowerInvulnerable")||
		CPlayer.mo.FindInventory("PowerBuddha")||CPlayer.mo.FindInventory("PowerInvisibility")||
		CPlayer.mo.FindInventory("PowerProtection")||CPlayer.mo.FindInventory("PowerIronFeet")) DrawImage("graphics/hud_powerup.png", (4,-44), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		if (CPlayer.mo.FindInventory("PowerStrength")) {
			DrawImage("graphics/hud_powerup_berserk.png", (4,-44), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		}
		if (CPlayer.mo.FindInventory("PowerInvulnerable")||CPlayer.mo.FindInventory("PowerBuddha")) {
			DrawImage("graphics/hud_powerup_god.png", (4,-44), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		}
		if (CPlayer.mo.FindInventory("PowerInvisibility")) {
			DrawImage("graphics/hud_powerup_invis.png", (4,-44), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		}
		if (CPlayer.mo.FindInventory("PowerProtection")||CPlayer.mo.FindInventory("PowerIronFeet")) {
			DrawImage("graphics/hud_powerup_protection.png", (4,-44), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		}
		DrawTexture(GetMugShot(5,Mugshot.XDEATHFACE), (5, -35), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		DrawImage("graphics/hud_healthnarmor.png", (44,-49), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		
		DrawString(mHUDFont, FormatNumber(mHealthInterpolator.GetValue(), 3, 3, FNF_FILLZEROS), (48, -41), DI_TRANSLATABLE);
		DrawString(mHUDFont, FormatNumber(mArmorInterpolator.GetValue(), 3, 3, FNF_FILLZEROS), (48, -20), DI_TRANSLATABLE);
		
		Inventory ammotype1, ammotype2;
		[ammotype1, ammotype2] = GetCurrentAmmo();

		// It should not draw the box if player is using a weapon that doesn't have ammo.
		if (ammotype2 != null && ammotype2 != ammotype1){
			DrawImage("graphics/hud_ammo.png", (-84,-35), DI_SCREEN_RIGHT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		} else if (ammotype1 != null) {
			DrawImage("graphics/hud_ammo_half.png", (-84,-35), DI_SCREEN_RIGHT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
		}

		int invY = -20;
		if (ammotype1 != null)
		{
			
			DrawInventoryIcon(ammotype1, (-18, -4), 0, 1.0, (15,15));
			DrawString(mHUDFont, FormatNumber(ammotype1.Amount, 3, 3, FNF_FILLZEROS), (-30, invY), DI_TEXT_ALIGN_RIGHT);
			invY -= 14;
			
		}
		if (ammotype2 != null && ammotype2 != ammotype1)
		{
			DrawInventoryIcon(ammotype2, (-18, -19), 0, 1.0, (15,15));
			DrawString(mHUDFont, FormatNumber(ammotype2.Amount, 3, 3, FNF_FILLZEROS), (-30, invY), DI_TEXT_ALIGN_RIGHT);
			invY -= 14;
		}
		if (!isInventoryBarVisible() && !Level.NoInventoryBar && CPlayer.mo.InvSel != null)
		{
			DrawInventoryIcon(CPlayer.mo.InvSel, (-14, invY + 17), DI_DIMDEPLETED);
			DrawString(mHUDFont, FormatNumber(CPlayer.mo.InvSel.Amount, 3), (-30, invY), DI_TEXT_ALIGN_RIGHT);
		}
		if (deathmatch)
		{
			DrawImage("graphics/hud_score.png", (-50, 2), DI_SCREEN_RIGHT_TOP|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
			DrawString(mHUDFont, FormatNumber(CPlayer.FragCount, 3, 3, FNF_FILLZEROS), (-4, 3), DI_TEXT_ALIGN_RIGHT);
		}
    BBDrawFullscreenKeys();
    
		if (isInventoryBarVisible())
		{
			DrawInventoryBar(diparms, (0, 0), 7, DI_SCREEN_CENTER_BOTTOM, HX_SHADOW);
		}
	}

	void BBDrawFullscreenKeys()
	{
		bool locks[6];
		String image;
		bool drawn = false;
		for(int i = 0; i < 6; i++) 
		{
			locks[i] = CPlayer.mo.CheckKeys(i + 1, false, true);
			// I'm too tired to find a better way to do this
			// is there something to check if a value is in an array in zscript?
			if (CPlayer.mo.CheckKeys(i + 1, false, true) && !drawn) 
			{
				drawn = true;
				DrawImage("graphics/hud_key.png", (90,-30), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS|DI_TRANSLATABLE);
			}
		}
		// key 1
		if (locks[1] && locks[4]) image = "STKEYS6";
		else if (locks[1]) image = "STKEYS0";
		else if (locks[4]) image = "STKEYS3";
		DrawImage(image, (92, -28), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		// key 2
		if (locks[2] && locks[5]) image = "STKEYS7";
		else if (locks[2]) image = "STKEYS1";
		else if (locks[5]) image = "STKEYS4";
		else image = "";
		DrawImage(image, (92, -20), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		// key 3
		if (locks[0] && locks[3]) image = "STKEYS8";
		else if (locks[0]) image = "STKEYS2";
		else if (locks[3]) image = "STKEYS5";
		else image = "";
		DrawImage(image, (92, -12), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
	}
}