#include "./weapons/deathshead.zsc" //writing "./" means the directory this file is at right now, so this translates to "zscript/"
#include "./weapons/spot.zsc"
#include "./weapons/doom.zsc"
#include "./weapons/chexquest.zsc"
#include "./weapons/heretic.zsc"

Class BlueBastardWeapon : Weapon //This will affect everyone's weapon if the weapon themselves don't have any value specific to them.
{
	Default
	{
	
	}
	Action void A_BBLefthand(int OverlayId) //This function is used on Ace's SSG.
	{
		A_OverlayFlags(OverlayId,PSPF_MIRROR|PSPF_FLIP,1);
		A_OverlayFlags(OverlayId,PSPF_ADDWEAPON,0);
		A_OverlayOffset(OverlayId,0,32);
	}
	states
	{
	
	}

}

class BlueBastardBulletPuff : BulletPuff
{
	Default
	{
		VSpeed 0;
		RenderStyle "Add";
		Alpha 0.8;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOINTERACTION;
		+FORCEXYBILLBOARD;
		Scale 0.5;
	}
	States
	{
	Crash:
		TNT1 A 0 
		{
			scale = default.scale*random(1.0,1.5);
			A_StartSound("misc/ricochet",CHAN_AUTO,CHANF_DEFAULT,random(0,1)*frandom(0.5,1.0));
		}
		TNT1 A 0 A_Jump(192,"Puff1","Puff2");
		Stop;
	Puff1:
		FX57 ABCDEFGHIJ 2 Bright;
		Stop;
	Puff2:
		FX58 ABCDEFGHIJ 2 Bright;
		Stop;
	}
}
class BlueBastardBulletPuffStab : BlueBastardBulletPuff {
	States {
	Crash:
		TNT1 A 0 {
			scale = default.scale*random(1.0,1.5);
			A_StartSound("weapons/claw/hitwall",CHAN_AUTO,CHANF_DEFAULT,0.8);
		}
		TNT1 A 0 A_Jump(256,"Puff1","Puff2");
		Stop;
	}
}
class BlueBastardBulletPuffSaw : BlueBastardBulletPuff { Default { +EXTREMEDEATH } }
class BlueBastardKickPuff : BulletPuff { Default { AttackSound "weapons/kick";} }
class BlueBastardPunchPuff : BulletPuff { Default { AttackSound "weapons/punch/hitwall";} }