class DeathsheadPistol : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "BBDeathshead9mm";
		Weapon.AmmoGive 20;
		Weapon.AmmoUse 1;
		
		Weapon.BobSpeed 1.5;
		
		+WEAPON.NOAUTOFIRE
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_PISTOL";
		Obituary "$OB_ACE_PISTOL";
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADPS FGHIJKL 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADPS L 2 A_StartSound("weapons/adpistol/deploy");
		ADPS KJIHGFEA 2;
	RealReady:
		ADPS A 1 A_WeaponReady;
		Wait;
	Fire:
		ADPS B 1 Bright
		{
			A_FireBullets (4, 2, -1, random(8,20), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/adpistol", CHAN_AUTO);
			A_GunFlash();
		}
		ADPS B 1 Bright A_WeaponReady(WRF_NOSWITCH);
		ADPS CD 2 Bright A_WeaponReady(WRF_NOSWITCH);
		ADPS EA 2 A_WeaponReady(WRF_NOSWITCH);
		Goto RealReady;
	Flash:
		ADPS M 2 Bright A_Light2;
		ADPS N 2 Bright A_Light1;
		Goto LightDone;
 	Spawn:
		ADPS A -1;
		Stop;
	}
}

class DeathsheadMAC10 : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "BBDeathshead9mm";
		Weapon.AmmoGive 20;
		Weapon.AmmoUse 1;
		
		Weapon.BobSpeed 1.5;
		
		Tag "$ACE_MAC10";
		Obituary "$OB_ACE_MAC10";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADMC D 1;
		ADMC E 2;
		ADMC F 1;
		ADMC G 2;
		ADMC H 1;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADMC H 1 A_StartSound("weapons/generic/draw");
		ADMC I 2;
		ADMC J 1;
		ADMC K 2;
		ADMC L 1;
		ADMC M 2 A_StartSound("weapons/mac10/deploy");
		ADMC N 1;
		ADMC O 2;
		ADMC P 1;
		ADMC Q 2;
		ADMC R 1;
		ADMC S 2;
	RealReady:
		ADMC A 1 A_WeaponReady;
		Loop;
	Fire:
		ADMC A 0 A_GunFlash;
		ADMC BC 2 Bright
		{
			A_FireBullets (13, 6, 4, random(3,5), "BlueBastardBulletPuff", FBF_NORANDOM);
			A_FireBullets (13, 6, -1, random(3,5), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/mac10", CHAN_AUTO);
			A_WeaponOffset(random(-4.0,8.0), random(32.0,48.0),WOF_INTERPOLATE);
		}
		ADMC A 0 A_ReFire;
		Goto RealReady;
	Flash:
		ADMC T 1 Bright A_Light2;
		ADMC U 1 Bright A_Light1;
		ADMC V 1 Bright A_Light2;
		ADMC W 1 Bright A_Light1;
		Goto LightDone;
	Spawn:
		ADMC A -1;
		Stop;
	}
}

class DeathsheadSG550Zoom : Inventory
{
	Default
	{
		Inventory.MaxAmount 1; 
	}
}
class DeathsheadSG550 : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "BBDeathshead556";
		Weapon.AmmoGive 10;
		Weapon.AmmoUse 1;
		
		Weapon.BobRangeX 1.25;
		
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_SG550";
		Obituary "$OB_ACE_SG550";
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADAS F 0 A_TakeInventory("DeathsheadSG550Zoom",1);
		ADAS F 2 A_ZoomFactor(1.0);
		ADAS G 1;
		ADAS H 2;
		ADAS I 1;
		ADAS J 2;
		ADAS K 1;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADAS K 1 A_StartSound("weapons/sg550/deploy");
		ADAS J 1;
		ADAS I 2;
		ADAS H 1;
		ADAS G 2;
		ADAS F 1;
	RealReady:
		ADAS A 1 A_WeaponReady;
		Wait;
	RealReadyZoomed:
		TNT1 A 1 A_WeaponReady;
		Wait;
	Fire:
		TNT1 A 0 A_JumpIfInventory("DeathsheadSG550Zoom",1,"FireZoomed");
		ADAS B 2 Bright
		{
			A_AlertMonsters();
			A_FireBullets (2, 3.5, -1, random(20,40), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/sg550", CHAN_AUTO);
			A_GunFlash();
			A_WeaponOffset(random(4.0,16.0), random(48.0,56.0),WOF_INTERPOLATE);
		}
		ADAS C 2 Bright;
		ADAS D 2;
		ADAS E 2 A_WeaponOffset(0.0, 32.0,WOF_INTERPOLATE);
		ADAS A 1;
		ADAS A 1 A_ReFire;
		Goto RealReady;
	FireZoomed:
		TNT1 A 0 Bright
		{
			A_AlertMonsters();
			A_FireBullets (0.5, 1, -1, random(20,40), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/sg550", CHAN_AUTO);
			A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
		}
		TNT1 AAA 2 Bright A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
		TNT1 AAA 1;
		TNT1 A 1 A_ReFire;
		Goto RealReadyZoomed;
	AltFire:
		ADAS N 0 A_StartSound("weapons/sg550/zoom", CHAN_AUTO);
		ADAS N 0 A_JumpIfInventory("DeathsheadSG550Zoom",1,"UnZoom");
		ADAS N 1;
		ADAS O 2;
		ADAS P 1;
		ADAS Q 2 A_ZoomFactor(1.25);
		ADAS R 1 A_ZoomFactor(1.5);
		ADAS S 2 A_ZoomFactor(1.75);
		ADAS S 0 {A_GiveInventory("DeathsheadSG550Zoom",1); A_ZoomFactor(2.0);}
		Goto AltHold;
	UnZoom:
		ADAS S 1 A_ZoomFactor(1.75);
		ADAS R 2 A_ZoomFactor(1.5);
		ADAS Q 1 A_ZoomFactor(1.25);
		ADAS P 2 A_ZoomFactor(1.0);
		ADAS O 1;
		ADAS N 2;
		ADAS A 1 A_TakeInventory("DeathsheadSG550Zoom",1);
		Goto AltHold;
	AltHold:
		TNT1 A 0 A_JumpIfInventory("DeathsheadSG550Zoom",1,3);
		ADAS A 1;
		TNT1 A 0 A_ReFire("AltHold");
		Goto RealReady;
		TNT1 A 1;
		TNT1 A 0 A_ReFire("AltHold");
		Goto RealReadyZoomed;
	Flash:
		ADAS L 2 Bright A_Light2;
		ADAS M 2 Bright A_Light1;
		Goto LightDone;
	}
}

class DeathsheadM4 : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType1 "BBDeathshead556";
		Weapon.AmmoType2 "BBDeathsheadGrenade";
		Weapon.AmmoUse1 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive1 20;
		Weapon.AmmoGive2 2;
		
		Tag "$ACE_M4";
		Obituary "$OB_ACE_M4";
		+INVENTORY.UNDROPPABLE
		+WEAPON.AMMO_OPTIONAL
		+WEAPON.ALT_AMMO_OPTIONAL
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADM4 F 1;
		ADM4 G 2;
		ADM4 H 1;
		ADM4 I 2;
		ADM4 J 1;
		ADM4 K 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADM4 K 1 A_StartSound("weapons/autoshotgun/deploy");
		ADM4 J 2;
		ADM4 I 1;
		ADM4 H 2;
		ADM4 G 1;
		ADM4 F 2;
		ADM4 E 1;
	RealReady:
		ADM4 A 1 A_WeaponReady;
		Loop;
	Fire:
		TNT1 A 0 A_JumpIfInventory("BBDeathshead556",1,1);
		Goto DryFire;
		ADM4 B 1 Bright
		{
			A_FireBullets (4.5, 3, -1, random(12,16), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/m4", CHAN_AUTO);
			A_WeaponOffset(random(-4.0,8.0), random(32.0,48.0),WOF_INTERPOLATE);
			A_GunFlash();
		}
		ADM4 C 2 Bright A_WeaponOffset(0.0, 32.0,WOF_INTERPOLATE);
		ADM4 DE 2 A_ReFire;
		Goto RealReady;
	DryFire:
		ADM4 B 2
		{
			A_WeaponOffset(random(-2.0,4.0), random(32.0,36.0),WOF_INTERPOLATE);
			A_StartSound("weapons/dryfire", CHAN_AUTO);
		}
		ADM4 C 2 A_WeaponOffset(0.0, 32.0,WOF_INTERPOLATE);
		ADM4 DE 2;
		Goto RealReady;
	AltFire:
		TNT1 A 0 A_JumpIfInventory("BBDeathsheadGrenade",1,1);
		Goto DryFire;
		ADM4 B 2 A_FireProjectile("DeathsheadM4Grenade",0,true,0,0,0,-6);
		ADM4 CDEA 2;
		ADM4 A 14 A_WeaponReady(WRF_NOSECONDARY);
		Goto RealReady;
	Flash:
		ADM4 L 1 Bright A_Light1;
		ADM4 M 2 Bright A_Light2;
		Goto LightDone;
	Spawn:
		ADMC A -1;
		Stop;
	}
}

class DeathsheadM4Grenade : Grenade
{
	Default
	{
		BounceType "None";
		SeeSound "weapons/m4/grenade";
		DeathSound "weapons/rocklx";
		Obituary "$OB_ACE_M4_GRENADE";
	}
}

