class DeathsheadPlasmaRifle : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.BobRangeX 1.25;
		Weapon.BobRangeY 0.75;
		Weapon.WeaponScaleX 0.9;
		Weapon.WeaponScaleY 1.08;
		
		Weapon.AmmoType1 "Cell";
		Weapon.AmmoUse1 5;
		Weapon.AmmoType2 "Cell";
		Weapon.AmmoUse2 5;
		Weapon.AmmoGive 40;
		Tag "$ACE_PLASMA";
		Obituary "$OB_ACE_PLASMA";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADPC GHIJKLM 1;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADPC M 1 A_StartSound("weapons/plasmacannon/deploy");
		ADPC LKJIHGA 1;
	RealReady:
		ADPC A 1 A_WeaponReady;
		Loop;
	Fire:
		ADPC B 2 Bright
		{
			A_StartSound("weapons/plasmacannon", CHAN_WEAPON);
			for (int i = 0; i < 5; i++)
			{
				A_FireProjectile("PlasmaCannonBall",random(-3.0,3.0),false,0,0,0,random(-3.0,3.0));
			}
			A_FireProjectile("PlasmaCannonBall",0,true);
			A_GunFlash();
		}
		ADPC C 2 Bright;
		ADPC DAAAAA 2;
		ADPC A 0 A_ReFire;
		Goto RealReady;
	AltFire:
		ADPC B 2 Bright
		{
			A_StartSound("weapons/railgun", CHAN_WEAPON);
			A_RailAttack(random(45,60), color1:"00c8ff", color2:"c1d6db", pufftype:null);
			A_GunFlash();
		}
		ADPC C 2 Bright;
		ADPC DAAAAA 2;
		ADPC A 0 A_ReFire;
		Goto RealReady;
	Flash:
		ADPC E 2 Bright A_Light1;
		ADPC F 2 Bright A_Light1;
		Goto LightDone;
	Spawn:
		PLAS A -1;
		Stop;
	}
}

class PlasmaCannonBall : PlasmaBall
{
	Default
	{
		Damage 4;
		Speed 50;
		SeeSound "";
	}
	States
	{
	Death:
		PLSE A 0 Bright A_Explode(random(1,10),96,0);
		PLSE A 4 Bright A_Explode(random(1,5),56,XF_HURTSOURCE);
		PLSE BCDE 4 Bright;
		Stop;
	}
}

class DeathsheadBFG : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "BBDeathsheadBFGCell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 1;
		
		Weapon.BobRangeX 1.5;
		Weapon.BobRangeY 0.5;
		
		Tag "$ACE_BFG";
		Obituary "$OB_ACE_BFG";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		NBFG AMLKJ 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		NBFG J 2 A_StartSound("weapons/bfgq2/deploy");
		NBFG KLMAA 2;
	RealReady:
		NBFG A 1 A_WeaponReady;
		Loop;
	Fire:
		NBFG A 0 A_StartSound("weapons/bfgq2", CHAN_AUTO); 
		NBFG AAAAAAAAAA 1 Bright A_WeaponOffset(random(-2.0,2.0), random(32.0,34.0),WOF_INTERPOLATE);
		NBFG CCDDBBCCD 1 Bright A_WeaponOffset(random(-4.0,4.0), random(32.0,36.0),WOF_INTERPOLATE);
		NBFG DBBCCDDBB 1 Bright A_WeaponOffset(random(-8.0,8.0), random(32.0,40.0),WOF_INTERPOLATE);
		NBFG E 2 Bright
		{
			A_WeaponOffset(16.0, 48.0, WOF_INTERPOLATE);
			//I don't get why you would need this when a_fireprojectile is there, i kept it just in case if it's needed later on.
			/*if (player == null)
			{
				return;
			}
			Weapon weap = player.ReadyWeapon;
			if (weap != null && invoker == weap && stateinfo != null && stateinfo.mStateType == STATE_Psprite)
			{
				if (!weap.DepleteAmmo (weap.bAltFire, true, deh.BFGCells))
					return;
			}
			SpawnPlayerMissile("DeathsheadBFGBall", angle, nofreeaim:sv_nobfgaim);*/
			A_FireProjectile("DeathsheadBFGBall");
		}
		NBFG F 2 Bright A_WeaponOffset(8.0, 8.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG G 2 Bright A_WeaponOffset(4.0, 4.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG H 2 Bright A_WeaponOffset(-4.0, -4.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG I 2 Bright A_WeaponOffset(-8.0, -8.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG A 2 Bright A_WeaponOffset(-16.0, -16.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG A 18;
		NBFG A 0 A_ReFire;
		Goto RealReady;
	}
}

class DeathsheadBFGBall : BFGBall
{
	Default
	{
		Damage 48;
		+FORCEXYBILLBOARD
		+BRIGHT
		+EXTREMEDEATH
	}
	States
	{
	Spawn:
		NBFB ABCD 2;
		Loop;
	Death:
		BFE1 A 8 Bright
		{
			A_Explode(128,128,0);
			A_Explode(64,256,0);
		}
		BFE1 B 8 Bright;
		BFE1 C 8 Bright A_BFGSpray;
		BFE1 DEF 8 Bright;
		Stop;
	}
}

