class DeathsheadFist : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.BobStyle "Smooth";
		Weapon.BobRangeX 1.5;
		
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_FISTS";
		Obituary "$OB_ACE_FISTS";
	}
	States
	{
	Select:
		ADFK A 1 A_Raise(24);
		Wait;
	Deselect:
		ADFK KL 2;
		ADFK L 1 A_Lower(24);
		Wait;
	Ready:
		ADFK ABCD 2;
		ADFK E 2 A_StartSound("weapons/fists/deploy");
		ADFK FGHIJ 2;
	RealReady:
		ADFS A 1 A_WeaponReady(WRF_ALLOWRELOAD);
		Wait;
	Fire:
		ADFS A 0 A_Jump(256, "FireRight", "FireLeft");
	FireRight:
		ADFS B 1;
		ADFS C 2 
		{
			int dmg = random(8,24);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardPunchPuff", range: meleeRange + 20, meleesound: "*fist", misssound: "weapons/swing");
		}
		ADFS D 2 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADFS EFGH 2 A_WeaponOffset(0.0, 32.0);
		ADFS A 2 A_ReFire;
		Goto RealReady;
	FireLeft:
		ADFS I 1;
		ADFS J 2 
		{
			int dmg = random(8,24);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardPunchPuff", range: meleeRange + 20, meleesound: "*fist", misssound: "weapons/swing");
		}
		ADFS K 2 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADFS LMNA 2 A_WeaponOffset(0.0, 32.0);
		ADFS A 2 A_ReFire;
		Goto RealReady;
	AltFire:
		ADFS A 0 A_Jump(256, "AltFireRight", "AltFireLeft");
	AltFireRight:
		ADGB A 2;
		ADGB B 1;
		ADGB C 2 
		{
			int dmg = random(2,48);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 2;
			}
			A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/impact", misssound: "weapons/swing");
		}
		ADGB D 1;
		ADGB E 2;
		ADGB F 1;
		ADGB G 2 A_ReFire;
		Goto RealReady;
	AltFireLeft:
		ADGB H 2;
		ADGB I 1;
		ADGB J 2 
		{
			int dmg = random(2,48);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 2;
			}
			A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/impact", misssound: "weapons/swing");
		}
		ADGB K 1;
		ADGB L 2;
		ADGB M 1;
		TNT1 A 2 A_ReFire;
		Goto RealReady;
	Reload:
		ADFK CD 2;
		ADFK E 2 A_StartSound("weapons/fists/deploy");
		ADFK FGHIJ 2;
		Goto RealReady;
	}
}

class DeathsheadChainsaw : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Tag "$ACE_CHAINSAW";
		Obituary "$OB_ACE_CHAINSAW";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		ADCS N 1 A_Raise(24);
		Wait;
	Deselect:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_StopSound(7);
		TNT1 A 0 A_StartSound("weapons/sawidle", 7, CHANF_DEFAULT, 0.75);
		ADCS KLMN 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADCS N 2 A_StartSound("weapons/generic/draw", CHAN_AUTO);
		ADCS OPQRSTU 2;
		ADCS V 2 A_StartSound("weapons/chainsaw/start", CHAN_AUTO);
		ADCS W 2 A_StartSound("weapons/sawup", CHAN_AUTO);
		ADCS XYZ[D 2;
	RealReady:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_StopSound(7);
		TNT1 A 0 A_StartSound("weapons/sawidle", 7, CHANF_DEFAULT, 0.75);
		ADCS ABCD 2 A_WeaponReady;
		Loop;
	Fire:
		TNT1 A 0 A_StartSound("weapons/sawfull", 6, CHANF_LOOPING, 0.75);
		ADCS E 1;
	Hold:
		ADCS F 0 A_Saw("","weapons/chainsaw",2,"BlueBastardBulletPuffSaw");
		ADCS FG 1
		{
			A_WeaponOffset(random(-2.0,2.0), random(32.0,40.0),WOF_INTERPOLATE);
		}
		ADCS H 0 A_Saw("","weapons/chainsaw",2,"BlueBastardBulletPuffSaw");
		ADCS HI 1
		{
			A_WeaponOffset(random(-2.0,2.0), random(32.0,40.0),WOF_INTERPOLATE);
		}
		ADCS J 1 A_ReFire;
		Goto RealReady;
	}
}


class DeathsheadKicky : CustomInventory
{
    States
    {
    Use:
		// I'm sure there's a better way but ehh
		TNT1 A 0 {
			int kick_type = random(1,2);
			if (kick_type == 1){
				A_Overlay(-2,"Kicky1",1);
			}
			else{
				A_Overlay(-2,"Kicky2",1);
			}
		}
        TNT1 A 0 A_OverlayOffset(-2,0,32);
        Fail;
    Kicky1:
        ADKK A 2 A_StartSound("weapons/kick/miss",CHAN_AUTO);
		ADKK B 2;
        ADKK C 2 {
			int dmg = random(10,20);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 6;
			}
			A_CustomPunch(dmg, norandom:true, flags: 0, pufftype: "BlueBastardKickPuff", range: meleeRange + 20, meleesound: "weapons/kick", misssound: "");
		}
        ADKK DEFA 2;
		TNT1 A 2;
        Stop;
    Kicky2:
        ADKK G 2 A_StartSound("weapons/kick/miss",CHAN_AUTO);
		ADKK H 2;
        ADKK I 2 {
			int dmg = random(10,20);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 6;
			}
			A_CustomPunch(dmg, norandom:true, flags: 0, pufftype: "BlueBastardKickPuff", range: meleeRange + 20, meleesound: "weapons/kick", misssound: "");
		}
        ADKK JKLG 2;
		TNT1 A 2;
        Stop;
    }
}
