class Mothman_Transform : CustomInventory {
    
    Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
		Inventory.RestrictedTo "Deathshead";
	}

    action void TryTransform()
    {
        A_Print("$ACE_TRANSFORM_INIT", 5);
        let ppawn = PlayerPawn(self);

        if (!ppawn){
            return;
        }

        if (ppawn.Alternative == null){
            A_PlaySound("misc/protect", CHAN_AUTO);
            A_Morph("DeathsheadMothman", 35 * 30, MRF_FULLHEALTH, "BlueBastardsTransformationFog", "BlueBastardsTransformationFog");
        }
    }

    States {
        Use:
            TNT1 A 0 TryTransform();
            stop;
    }
}

class Mothman_Transform_End : CustomInventory {
    Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
		Inventory.RestrictedTo "Deathshead";
	}

    States {
        Use:
            TNT1 A 0 {
				A_PlaySound("misc/protect/end", CHAN_AUTO);
				A_Print("$ACE_TRANSFORM_WORN", 3);
			}
            Stop;
    }
}

class MothmanWhiskeyBottle : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.BobStyle "Smooth";
		Weapon.BobRangeX 1.5;
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_FISTS";
		Obituary "$OB_ACE_MOTHMAN_MELEE";
	}
	States
	{
	Select:
		MFMW A 1 A_Raise(24);
		Wait;
	Deselect:
		MFMW A 1 A_Lower(24);
		Wait;
	Ready:
		MFMW A 1 A_WeaponReady;
		Wait;
	Fire:
		MFMW A 0 A_Jump(256, "FireRight", "FireLeft");
	FireRight:
		MFMW B 1 A_PlaySound("weapons/swing", CHAN_AUTO);
		MFMW CD 1;
		MFMW E 1 A_CustomPunch(random(75,200), norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/rip");
		MFMW FGHI 1;
		MFMW JKLM 1 A_ReFire;
		Goto Ready;
	FireLeft:
		MFMW N 1 A_PlaySound("weapons/swing", CHAN_AUTO);
		MFMW OP 1;
		MFMW Q 1 A_CustomPunch(random(75,200), norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/rip");
		MFMW RSTU 1;
		MFMW VWAA 1 A_ReFire;
		Goto Ready;
	AltFire:
		MFMM AB 1;
		MFMM C 1 A_PlaySound("weapons/flame", CHAN_AUTO);
		MFMM DEF 1 A_FireProjectile("MothmanFire");
	AltHold:
		MFMM F 1 A_FireProjectile("MothmanFire");
		MFMM EDCBA 1 A_ReFire;
	}
}

class MothmanFire : Actor
{
	Default
	{
		Radius 6;
		Height 8;
		Speed 20;
		Damage 4;
		DamageType "Fire";
		Projectile;
		RenderStyle "Add";
		Obituary "$OB_ACE_MOTHMAN";
	}
	States
	{
	Spawn:
		BAL1 ABABABABABABCDE 2 Bright;
		Stop;
	Death:
		BAL1 CDE 2 Bright RadiusAttack(target,2,64);
		Stop;
	}
}