class DeathsheadRocketLauncher : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "Rocketammo";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 2;
		Weapon.BobRangeX 1.5;
		Weapon.BobRangeY 0.5;
		
		Tag "$ACE_ROCKET";
		Obituary "$OB_ACE_ROCKET";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADRK JIHGF 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADRK F 2 A_StartSound("weapons/rocket/load");
		ADRK GHIJA 2;
	RealReady:
		ADRK A 1 A_WeaponReady;
		Loop;
	Fire:
		ADRK B 0
		{
			A_StartSound("weapons/rocket", CHAN_AUTO);
			A_FireMissile();
		}
		ADRK BC 2 Bright A_WeaponOffset(8.0, 8.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK DE 2 Bright A_WeaponOffset(2.0, 2.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK A 0 A_StartSound("weapons/rocket/load", CHAN_AUTO, CHANF_DEFAULT, 0.5);
		ADRK AA 2 Bright A_WeaponOffset(-2.0, -2.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK AA 2 Bright A_WeaponOffset(-8.0, -8.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK A 2 A_ReFire;
		Goto RealReady;
	}
}