class DeathsheadShotgun : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.BobRangeY 0.5;
		Weapon.BobRangeX 1;
		Tag "$ACE_AUTOSHOTGUN";
		Obituary "$OB_ACE_AUTOSHOTGUN";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADSG GHIJKLM 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADSG M 2 A_StartSound("weapons/autoshotgun/deploy");
		ADSG LKJIHGA 2;
	RealReady:
		ADSG A 1 A_WeaponReady;
		Loop;
	Fire:
		ADSG B 1 Bright
		{
			A_FireBullets (6, 6, 12, random(2,5), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/autoshotgun", CHAN_AUTO);
			A_GunFlash();
		}
		ADSG C 2 Bright;
		ADSG D 2 Bright;
		ADSG EFA 2 A_ReFire;
		Goto RealReady;
	Flash:
		ADSG N 1 Bright A_Light2;
		ADSG O 2 Bright A_Light1;
		Goto LightDone;
	}
}

class DeathsheadSuperShotgun : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 4;
		Weapon.AmmoGive 16;
		
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1;
		
		Tag "$ACE_SAWNOFFS";
		Obituary "$OB_ACE_SAWNOFFS";
		+INVENTORY.UNDROPPABLE;
	}
	
    States
	{
	Select: //While the A_Raise(24) seems to work perfectly, 
		TNT1 A 0 offset(0,32) A_Overlay(2,"LeftSelect");
		ADDB I 2 A_StartSound("weapons/sshotc", CHAN_AUTO);
		ADDB HGFE 2;//you can use Offset(0,32) prior to just force the movement forward and then make it go to ready, 
		Goto Ready; //works just as the other, except you can add an action afterwards.
	LeftSelect:
		TNT1 A 0 A_BBLefthand(OverlayId());
		ADDB I 2 A_StartSound("weapons/sshotc", CHAN_AUTO);
		ADDB HGFE 2;
		goto LeftReady;
	Deselect:
		ADDB A 0 {
			A_Overlay(2,"LeftDeselect");
			A_BBLefthand(2);
		}
		ADDB EFGHI 2;
		ADDB I 1 A_Lower(24);
		Wait;
	LeftDeselect:
		ADDB EFGHI 2;
		ADDB I 1;
		Wait;
		
		
	Ready:
		ADDB A 1 A_WeaponReady(); 
		//ADDB A 0 A_JumpIf(GetPlayerInput(INPUT_BUTTONS) & BT_ATTACK, "Fire"); //I don't get the usage of Input checking here when weaponready can cover both sides, in my opinion.
		loop;
	LeftReady:
		ADDB A 1;// A_JumpIf(GetPlayerInput(INPUT_BUTTONS) & BT_ATTACK, "LeftFire");
		wait;

	Fire:
		TNT1 A 0 A_Overlay(2,"LeftFire");
		ADDB M 2 Bright {
			A_FireBullets(12.8, 8.2, 48, random(3,6), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/shotgun/fire", CHAN_AUTO);
			A_StartSound("weapons/doubleshotties", CHAN_AUTO, CHANF_DEFAULT, 0.3);
			A_GunFlash();
			A_quake(3,2,0,16);
			A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
			A_Recoil(5*cos(pitch));
			a_overlay(4,"KnockbackFX");
		}
		ADDB N 2 Bright{
			A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
			A_overlayOffset(2,Random(-2,2),Random(-2,2) + 36);
			A_overlayOffset(1,Random(-2,2),Random(-2,2) + 36);
		}
		ADDB CCCCC 2{
			A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
			A_overlayOffset(2,Random(-2,2),Random(-2,2) + 36);
			A_overlayOffset(1,Random(-2,2),Random(-2,2) + 36);
		}
		ADDB D 2;
		ADDB A 0 A_CheckReload;
		ADDB EFG 2;
		ADDB H 2 A_StartSound("weapons/sshoto", CHAN_AUTO);
		ADDB I 2 A_StartSound("weapons/sshotl", CHAN_AUTO);
		ADDB J 2 A_StartSound("weapons/sshotc", CHAN_AUTO);
		ADDB KLC 2;
		Goto Ready;
	LeftFire:
		TNT1 A 0 A_BBLefthand(OverlayId());
		ADDB M 2 Bright;
		ADDB N 2 Bright;
		ADDB C 10;
		ADDB DEFGHIJKLC 2;
		Goto Ready;
	Flash:
		TNT1 A 2 A_Light1;
		TNT1 A 2 A_Light2;
		Goto LightDone;
		
	KnockbackFX:
		TNT1 A 2
		{
			A_overlayscale(PSP_WEAPON,1.6); //PSP_WEAPON is the equivalent of layer 1 in the overlays.
			A_overlayscale(2,1.6); //PSP_FLASH is the overlay that gunflash uses
		}
		TNT1 A 2
		{
			A_overlayscale(1,1.5);
			A_overlayscale(2,1.5);
		}
		TNT1 A 2;
		TNT1 A 1
		{
			A_overlayscale(1,1.45);
			A_overlayscale(2,1.45);
		}
		TNT1 A 1
		{
			A_overlayscale(1,1.40);
			A_overlayscale(2,1.40);
		}
		TNT1 A 2
		{
			A_overlayscale(1,1.35);
			A_overlayscale(2,1.35);
		}
		TNT1 A 2
		{
			A_overlayscale(1,1.15);
			A_overlayscale(2,1.15);
		}
		TNT1 A 2
		{
			A_overlayscale(1,1.05);
			A_overlayscale(2,1.05);
		}
		TNT1 A 1
		{
			A_overlayscale(1,1);
			A_overlayscale(2,1);
		}
		stop;
	}
}
