class HealthBonusSpawner : RandomSpawner replaces HealthBonus
{
    Default
    {
        DropItem "DrGibbCan";
        DropItem "DrGibbGlass";
        DropItem "WhiskeyGlass";
		DropItem "HalfPigInABlanket";
		DropItem "HalfBurger";
		DropItem "MreBiscuit";
		DropItem "ChipCrumb";
    }
}

class StimPackSpawner : RandomSpawner replaces StimPack
{
    Default
    {
        DropItem "WhiskeyBottle";
        DropItem "VodkaBottle";
		DropItem "MysteryCan";
    }
}

class MedikitSpawner : RandomSpawner replaces Medikit
{
    Default
    {
        DropItem "ChickenHeal";
        DropItem "Medkit_Mslug";
    }
}

class BlueBastardBackpack : Backpack replaces Backpack
{
	Default
	{
		Inventory.PickupMessage "$GOTBACKPACK";
		Inventory.PickupSound "misc/metalslug";
	}
	States
	{
	Spawn:
		BPAK A 16;
		BPAK BCDEF 2;
		Loop;
	}
}

class SoulsphereReplacement : Soulsphere replaces Soulsphere
{
	override bool TryPickup (in out Actor other)
	{
		PrevHealth = other.player != NULL ? other.player.health : other.health;
		
		int blehhh = 200;
		if (other.FindInventory("SpotMallet"))
		{
			blehhh += 50;
		}
		if (other.GiveBody(Amount, blehhh))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}


class BBClip : BBAmmoDistributor replaces clip
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIP";
		/*Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 400;
		Inventory.Icon "CLIPA0";*/
		Tag "$AMMO_CLIP";
	}
	States
	{
	Spawn:
		CLIP A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{

			if (CheckInventory("SpotMallet", 1)) 
			{
	
				if(A_AllowedToGrab("BBSpot600") || A_AllowedToGrab("BBSpotNavalBullets") || A_AllowedToGrab("Clip"))
				{
					
					A_GiveInventory("BBSpot600", A_ammomultiplier(2), false);
					A_GiveInventory("BBSpotNavalBullets", A_ammomultiplier(10), false);
					A_GiveInventory("Clip", A_ammomultiplier(10), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				if(A_AllowedToGrab("BBDeathshead9mm") || A_AllowedToGrab("BBDeathshead556"))
				{
					A_GiveInventory("BBDeathshead9mm", A_ammomultiplier(10), false);
					A_GiveInventory("BBDeathshead556", A_ammomultiplier(10), false);
					return resolvestate(Null);
				} else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		stop;	
		
	}
}
	

class BBClipBox : BBAmmoDistributor replaces clipbox
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIPBOX";
		/*Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 400;
		Inventory.Icon "CLIPA0";*/
		Tag "$AMMO_CLIP";
	}
	States
	{
	Spawn:
		AMMO A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("BBSpot600") || A_AllowedToGrab("BBSpotNavalBullets") || A_AllowedToGrab("Clip"))
				{
					A_GiveInventory("BBSpot600", A_ammomultiplier(10), false);
					A_GiveInventory("BBSpotNavalBullets", A_ammomultiplier(50), false);
					A_GiveInventory("Clip", A_ammomultiplier(50), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				if(A_AllowedToGrab("BBDeathshead9mm") || A_AllowedToGrab("BBDeathshead556"))
				{
					A_GiveInventory("BBDeathshead9mm", A_ammomultiplier(50), false);
					A_GiveInventory("BBDeathshead556", A_ammomultiplier(50), false);
					return resolvestate(Null);
				} else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;

	}
}

class BBShell : BBAmmoDistributor replaces Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLS";
		/*Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "SHELA0";*/
		Tag "$AMMO_SHELLS";
	}
	States
	{
	Spawn:
		SHEL A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("BBSpotDevastatorShell") || A_AllowedToGrab("Shell")) 
				{ 
					A_GiveInventory("BBSpotDevastatorShell", A_ammomultiplier(4), false);
					A_GiveInventory("Shell", A_ammomultiplier(4), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				if(A_AllowedToGrab("Shell"))
				{
					A_GiveInventory("Shell", A_ammomultiplier(4), false);
					return resolvestate(null);			
				}else return resolvestate("cantpickup");
			}
			return resolvestate(null);
			
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;
	
	}
}

class BBShellBox : BBAmmoDistributor replaces ShellBox
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLBOX";
	}
	States
	{
	Spawn:
		SBOX A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("BBSpotDevastatorShell") || A_AllowedToGrab("Shell")) 
				{ 
					A_GiveInventory("Shell", A_ammomultiplier(20), false);
					A_GiveInventory("BBSpotDevastatorShell", A_ammomultiplier(10), false);
				return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				if(A_AllowedToGrab("Shell"))
				{
					A_GiveInventory("Shell", A_ammomultiplier(20), false);
					return resolvestate(null);			
				}else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;

	}
}

class BBRocketAmmo : BBAmmoDistributor replaces RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKET";
		Tag "$AMMO_ROCKETS";
	}
	States
	{
	Spawn:
		ROCK A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("RocketAmmo")) 
				{ 
					A_GiveInventory("RocketAmmo", 1, false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				if(A_AllowedToGrab("BBDeathsheadGrenade") || A_AllowedToGrab("RocketAmmo")) 
				{ 
					A_GiveInventory("BBDeathsheadGrenade", A_ammomultiplier(2), false);
					A_GiveInventory("RocketAmmo", 1, false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;
	}
}
	

class BBRocketBox : BBAmmoDistributor replaces RocketBox
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKBOX";
	}
	States
	{
	Spawn:
		BROK A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{

			
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("RocketAmmo")) 
				{ 
					A_GiveInventory("RocketAmmo", A_ammomultiplier(5), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				if(A_AllowedToGrab("BBDeathsheadGrenade") || A_AllowedToGrab("RocketAmmo")) 
				{ 
					A_GiveInventory("BBDeathsheadGrenade", A_ammomultiplier(5), false);
					A_GiveInventory("RocketAmmo", A_ammomultiplier(5), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;
	}
}

class BBCell : BBAmmoDistributor replaces Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTCELL";
		Tag "$AMMO_CELLS";
	}

	States
	{
	Spawn:
		CELL A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("Cell") || A_AllowedToGrab("BBSpotAtomicBomb")) 
				{ 
					A_GiveInventory("BBSpotAtomicBomb", 1, false);
					A_GiveInventory("Cell", A_ammomultiplier(20), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
				
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				if(A_AllowedToGrab("Cell") || A_AllowedToGrab("BBDeathsheadBFGCell")) 
				{ 
					A_GiveInventory("BBDeathsheadBFGCell", 1, false);
					A_GiveInventory("Cell", A_ammomultiplier(20), false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;
	}
}

class BBCellPack : BBAmmoDistributor replaces CellPack
{
	Default
	{
		Inventory.PickupMessage "$GOTCELLBOX";
	}
	States
	{
	Spawn:
		CELP A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			
			if (CheckInventory("SpotMallet", 1)) 
			{
				if(A_AllowedToGrab("Cell") || A_AllowedToGrab("BBSpotAtomicBomb")) 
				{ 
					A_GiveInventory("Cell", A_ammomultiplier(100), false);
					A_GiveInventory("BBSpotAtomicBomb", 2, false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				if(A_AllowedToGrab("Cell") || A_AllowedToGrab("BBDeathsheadBFGCell")) 
				{
					A_GiveInventory("Cell", A_ammomultiplier(100), false);
					A_GiveInventory("BBDeathsheadBFGCell", 2, false);
					return resolvestate(null);
				}else return resolvestate("cantpickup");
			}
			return resolvestate(null);
		}
		TNT1 A 1 A_Railwait(); //This function does nothing, but the entire anonymous function system would always fail if there was no function afterwards...
		Stop;
	}
}