class BagOfHoldingReplacement : RandomSpawner replaces BagOfHolding
{
	Default
	{
		DropItem "BlueBastardBackpack";
	}
}

class BlasterAmmoReplacement : BBClip replaces BlasterAmmo
{
	States
	{
	Spawn:
		AMB1 ABC 4;
		Loop;
	}
}

class BlasterHeftyReplacement : BBClipBox replaces BlasterHefty
{
	States
	{
	Spawn:
		AMB2 ABC 4;
		Loop;
	}
}

class CrossbowAmmoReplacement : BBShell replaces CrossbowAmmo
{
	States
	{
	Spawn:
		AMC1 A -1;
		Stop;
	}
}

class CrossbowHeftyReplacement : BBShellBox replaces CrossbowHefty
{
	States
	{
	Spawn:
		AMC2 ABC 5;
		Loop;
	}
}

class GoldWandAmmoReplacement : BBClip replaces GoldWandAmmo
{
	States
	{
	Spawn:
		AMG1 A -1;
		Stop;
	}
}

class GoldWandHeftyReplacement : BBClipBox replaces GoldWandHefty
{
	States
	{
	Spawn:
		AMG2 ABC 4;
		Loop;
	}
}

class MaceAmmoReplacement : BBCell replaces MaceAmmo
{
	States
	{
	Spawn:
		AMM1 A -1;
		Stop;
	}
}

class MaceHeftyReplacement : BBCellPack replaces MaceHefty
{
	States
	{
	Spawn:
		AMM2 A -1;
		Stop;
	}
}

class PhoenixRodAmmoReplacement : BBRocketAmmo replaces PhoenixRodAmmo
{
	States
	{
	Spawn:
		AMP1 ABC 4;
		Loop;
	}
}

class PhoenixRodHeftyReplacement : BBRocketBox replaces PhoenixRodHefty
{
	States
	{
	Spawn:
		AMP2 ABC 4;
		Loop;
	}
}

class SkullRodAmmoReplacement : BBCell replaces SkullRodAmmo
{
	States
	{
	Spawn:
		AMS1 AB 5;
		Loop;
	}
}

class SkullRodHeftyReplacement : BBCellPack replaces SkullRodHefty
{
	States
	{
	Spawn:
		AMS2 AB 5;
		Loop;
	}
}