class AmmoSatchelReplacement : BlueBastardBackpack replaces AmmoSatchel
{
}

class BoxOfBulletsReplacement : BBClipbox replaces BoxOfBullets
{
	States
	{
	Spawn:
		BBOX A -1;
		Stop;
	}
}

class ClipOfBulletsReplacement : BBClip replaces ClipOfBullets
{
	States
	{
	Spawn:
		BLIT A -1;
		Stop;
	}
}

class ElectricBoltsReplacement : BBShell replaces ElectricBolts
{
	States
	{
	Spawn:
		XQRL A -1;
		Stop;
	}
}

class EnergyPackReplacement : BBCellPack replaces EnergyPack
{
	States
	{
	Spawn:
		CPAC AB 6;
		Loop;
	}
}

class EnergyPodReplacement : BBCell replaces EnergyPod
{
	States
	{
	Spawn:
		BRY1 AB 6;
		Loop;
	}
}

class HEGrenadeRoundsReplacement : BBRocketAmmo replaces HEGrenadeRounds
{
	States
	{
	Spawn:
		GRN1 A -1;
		Loop;
	}
}

class CrateOfMissilesReplacement : BBRocketBox replaces CrateOfMissiles
{
	States
	{
	Spawn:
		ROKT A -1;
		Loop;
	}
}

class MiniMissilesReplacement : BBRocketAmmo replaces MiniMissiles
{
	States
	{
	Spawn:
		MSSL A -1;
		Loop;
	}
}

class PhosphorusGrenadeRoundsReplacement : BBRocketAmmo replaces PhosphorusGrenadeRounds
{
	States
	{
	Spawn:
		GRN2 A -1;
		Loop;
	}
}

class PoisonBoltsReplacement : BBShell replaces PoisonBolts
{
	States
	{
	Spawn:
		PQRL A -1;
		Loop;
	}
}