class SpotExpress600 : BlueBastardWeapon
{
	mixin BBSpotWeapon;
    Default
    {
        Weapon.AmmoUse 1;
		Weapon.AmmoGive 5;
        Weapon.AmmoType "BBSpot600";
		Tag "$SPOT_REV";
		Obituary "$SPOT_KILL_REV";
		
		+INVENTORY.UNDROPPABLE
    }

	States
	{
	Deselect:
		REVR ABCDE 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		REVR EDC 2;
		REVR A 0 A_PlaySound("weapons/generic/draw");
		REVR BA 2;
	RealReady:
		BREV A 1 A_WeaponReady;
		Loop;
	Fire:
		BREV A 0 A_PlaySound("weapons/express600/prefire");
        BREV BBBBBBBBBB 1{
			A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
		}
        BREV A 2
        {   
            A_GunFlash();
			A_FireBullets(4,0,0,Random(45,60), "BlueBastardBulletPuff", FBF_NORANDOM||FBF_USEAMMO);
            A_PlaySound("weapons/express600/fire", CHAN_WEAPON);
			A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
        }
		BREV C 0 A_Recoil(1);
		BREV CD 2 A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
		BREV E 2{
			A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			A_ReFire();
		}
        Goto RealReady;
    Flash:
        REVF A 2 Bright A_Light1;
        TNT1 A 1 A_Light0;
        stop;
	}
}


class SpotChaingun : BlueBastardWeapon
{
	mixin BBSpotWeapon;
	Default
	{
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 10;
		Weapon.AmmoType "BBSpotNavalBullets";
		Inventory.PickupMessage "$GOTCHAINGUN";
		Obituary "$SPOT_KILL_NAVAL";

		Tag "$SPOT_NAVAL";

		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Deselect:
		SCGR ABCDE 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		SCGR EDC 2;
		SCGR B 0 A_PlayWeaponSound("weapons/chaingun/deploy");
		SCGR BA 2;
	RealReady:
		SCHG A 1 A_WeaponReady;
		Loop;
	Fire:
		SCHG AAA 2{
			A_FireBullets(8.5,4.5,3,10,"BlueBastardBulletPuff");
			A_PlayWeaponSound("weapons/chaingun/fire");
			A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
			A_SetPitch(self.pitch - 3, SPF_INTERPOLATE);
			A_Recoil(2);
			A_GunFlash("Flash");
		}
		SCHG BBBBBBBBBCCCCCCDDD 1{
			A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			A_SetPitch(self.pitch + 0.5, SPF_INTERPOLATE);
		}
		SCHG B 0 A_ReFire();
		Goto RealReady;
	Flash:
		SCGF A 1 Bright A_Light1;
		Goto LightDone;
	}
}

class SpotM249: BlueBastardWeapon
{
	mixin BBSpotWeapon;
	Default
	{
		Weapon.SelectionOrder 720;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Clip";
		Inventory.PickupMessage "$GOTCHAINGUN";
		Obituary "$SPOT_KILL_M249";

		Tag "$SPOT_M249";

		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Deselect:
		SM4R ABCDE 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		SM4R EDC 2;
		SM4R B 0 A_PlayWeaponSound("weapons/m249/deploy");
		SM4R BA 2;
	RealReady:
		SM24 A 1 A_WeaponReady;
		Loop;
	Fire:
		SM24 A 1{
			A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			A_FireBullets(4,2,1,10,"BlueBastardBulletPuff");
			A_PlayWeaponSound("weapons/m249/fire");
			A_SetPitch(self.pitch - 2, SPF_INTERPOLATE);
			A_Recoil(0.2);
			A_GunFlash("Flash");
		}
		SM24 BC 1{
			A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
		}
		SM24 DE 2 A_ReFire();
		Goto RealReady;
	Flash:
		SM4F A 1 Bright A_Light2;
		SM4F B 1 Bright A_Light1;
		Goto LightDone;
	}
}