
class SpotPlasmaRifle : PlasmaRifle
{
			Default{
		Weapon.AmmoType "Cell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.NOAUTOFIRE
		+INVENTORY.UNDROPPABLE

		Obituary "$SPOT_KILL_LASER";

		Tag "$SPOT_LASER";
	}
	States {
		Deselect:
			LSRL ABCDE 2 A_StopSound(CHAN_6);
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			LSRL EDC 2;
			LSRL A 0 A_PlaySound("weapons/rocket/load");
			LSRL BA 2;
		RealReady:
			LASR A 1 A_WeaponReady;
			Loop;
		Fire:
			LASR A 0 A_PlaySound("weapons/laser/start", CHAN_6, 1, false);
			LASR B 2;
			LASR A 0 A_PlaySound("weapons/laser/fire", CHAN_6, 1, true);
		RealFire:
			LSRF ABC 1 Bright {
				int dmg = Random(5,25);
				A_RailAttack(dmg,0,true,"", "#8f8fff", RGF_SILENT|RGF_NORANDOMPUFFZ, 0, "BulletPuff", 0.5, 0.5, 0, 2, 0.5, 0);
				A_Light(Random(2,4));
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 40);
			}
			LASR B 0 A_ReFire("RealFire");
			LASR A 0 A_StopSound(CHAN_6);
			LASR A 0 A_PlaySound("weapons/laser/stop", CHAN_6, 1, false);
			LASR BBBBBBBBBBBBBBB 1{
				A_Light0();
				A_WeaponOffset(Random(-1,1),Random(-1,1) + 40);
			}
			goto RealReady;
	}
}


class SpotBFG : BFG9000
{
		Default
	{
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 40;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		+WEAPON.NOAUTOFIRE;
		+INVENTORY.UNDROPPABLE

		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Weapon.BobStyle "InverseSmooth";

		Tag "$SPOT_MOFFOBLI";
	}
	States
	{
		Deselect:
			SFMR FEDCBA 3;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SFMR ABC 3;
			SFMR A 0 A_PlaySound("weapons/missle/deploy");
			SFMR DEF 3;
		RealReady:
			SFTM A 1 A_WeaponReady;
			Loop;
		Fire:
			SFTM A 0 A_PlaySound("weapons/nuke/alarm", CHAN_AUTO);
			SFTM AAAAAAAAAAAAAAA 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
			}
			SFTM AAAAAAA 1 {
				A_WeaponOffset(Random(-5,5),Random(-5,5) + 35);
			}
			SFTM BC 2;
			STMF D 0{
				A_QuakeEx(0.2,0.2,0.2, 15, 0, QF_RELATIVE, "");
				A_FireProjectile("SpotNuke");
				A_Recoil(4);
				A_SetPitch(self.pitch - 8);
				A_PlaySound("weapons/nuke", CHAN_AUTO);
			}
			SFTM DDDD 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			}
			SFTM DDDDDDDDDDDD 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
			}
			SFTM D 3 A_CheckReload();
			SFTM EFG 3;
			TNT1 A 15;
			TNT1 A 0 A_PlaySound("weapons/nuke/load", CHAN_AUTO);
			TNT1 A 35;
			SFMR ABC 3;
			SFMR A 0 A_PlaySound("weapons/missle/deploy");
			SFMR DEF 3;
			SFMR F 3 A_ReFire();
			Goto RealReady;
	}
}

class SpotNuke : Actor
{
	Default
	{
		Radius 32;
		Height 32;
		Speed 40;
		Damage 150;
		Projectile;
		//DeathSound "weapons/nuke/explode";
		+DEHEXPLOSION
		+ROCKETTRAIL
		+ZDOOMTRANS
		+EXTREMEDEATH
	}

	States
	{
		Spawn:
			SNUK A 1;
			Loop;
		Death:
			MISL B 0{
				A_QuakeEx( 3, 3, 3, 90, 0, 3000 );
				RadiusAttack(target,400,300);
				A_PlaySound("weapons/nuke/explode", CHAN_AUTO, 1, false, 0.02);
			} 
			// OMFG
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-32,32),random(-32,32),0);
			}
			MISL B 8 Bright A_Explode;
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-48,48),random(-48,48),0);
			}
			MISL C 6 Bright A_Light(10);
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-64,64),random(-64,64),0);
			}
			MISL D 4 Bright A_Light(0);
			
			Stop;
	}
}

class NukeFlame : Actor
{
	Default
	{
		Radius 32;
		Height 16;
		Scale 2.0;
		Speed 40;
		Damage 150;
		DeathSound "weapons/nuke/explode";
		Obituary "$SPOT_KILL_NUKEFIRE";
		+RANDOMIZE
		+ROCKETTRAIL
		+ZDOOMTRANS
		+EXTREMEDEATH
	}

	States
	{
		Spawn:
			NFRL A 0;
		Death:
			NFRL ABCDEFGHIJKLABCDEFGHIJKL 2 bright{
				A_Fire();
				RadiusAttack(target,30,64);
			}
			NFRD ABCDEFGHIJKLMNO 2 bright RadiusAttack(target,30,64);
			Stop;
	}
}



