class Dragon_Spot_Transform : CustomInventory {
    action void TryTransform()
    {
        let ppawn = PlayerPawn(owner);

        if (!ppawn){
            return;
        }

        if (!ppawn.Alternative){
            A_PlaySound("misc/berserk");
            A_Morph("SpotDragon", 35 * 5, MRF_FULLHEALTH);
        }
    }

    States {
        Use:
            TNT1 A 0 TryTransform();
            stop;
    }
}