class Dragon_Spot_Transform : CustomInventory {
   
    Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
		Inventory.RestrictedTo "Spot";
	}

    action void TryTransform()
    {
        A_Print("$SPOT_TRANSFORM_INIT", 5);
        let ppawn = PlayerPawn(self);

        if (!ppawn){
            return;
        }

        if (ppawn.Alternative == null){
            A_PlaySound("misc/protect", CHAN_AUTO);
            A_Morph("SpotDragon", 35 * 30, MRF_FULLHEALTH, "BlueBastardsTransformationFog", "BlueBastardsTransformationFog");
        }
    }

    States {
        Use:
            TNT1 A 0 TryTransform();
            stop;
    }
}

// this is atrocious lol
class Dragon_Spot_Transform_End : CustomInventory {
    Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
		Inventory.RestrictedTo "Spot";
	}

    States {
        Use:
            TNT1 A 0 A_PlaySound("misc/protect/end", CHAN_AUTO);
            stop;
    }
}


// Gao :3
class BBSpot_Dragon_Claws : BlueBastardWeapon 
{
    mixin BBSpotWeapon;
    int which_claw;

    Default
	{
		+WEAPON.MELEEWEAPON
        Tag " ";


		Weapon.BobSpeed 2.5;
		Weapon.BobRangeX 0;
		Weapon.BobRangeY 1;
	}

    override void PostBeginPlay(){
        Super.PostBeginPlay();
        which_claw = 0;
    }

    States
	{
	Deselect:
        DCWR ABCDEF 2;
		TNT1 A 0 A_Lower(24); 
		Loop;
	Select:
		TNT1 A 0 A_Raise(24);
		Loop;
    Ready:
		DCWR FEDCBA 2;
    RealReady:
        DGCI ABCB 4 A_WeaponReady;
        Loop;
	Fire:
        TNT1 A 0{

            // Probably possible to do it in a single line, but it works for now.
            invoker.which_claw += 1;
            invoker.which_claw = invoker.which_claw % 2;

            switch(invoker.which_claw)
            {
                case 0:
                    return ResolveState("Claw_Left");
                    break;
                case 1: 
                    return ResolveState("Claw_Right");
                    break;
            }
            return ResolveState(null);
        }
		stop;
    Claw_Left:
        DGCL A 1 A_PlaySound("weapons/swing", CHAN_AUTO);
		DGCL B 1;
        DGCL C 1 A_CustomPunch(random(50,150), norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/rip");
        DGCL DE 1;
        DCWR FDB 1 A_Refire("Fire");
        Goto RealReady;
    Claw_Right:
        DGCL A 1 A_PlaySound("weapons/swing", CHAN_AUTO);
		DGCL B 1;
        DGCR C 1 A_CustomPunch(random(50,150), norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/rip");
        DGCR DE 1;
        DCWR FDB 1 A_Refire("Fire");
        Goto RealReady;
    AltFire:
        DGFR AB 2;
		DGFR C 2 A_PlaySound("weapons/flame", CHAN_AUTO);
    HoldAlt:
        DGFR C 2{
            A_WeaponOffset(Random(-2,2),Random(-2,2)+36);
            A_FireProjectile("BBDragonFireBall", 0, 0 ,0);
        }
        DGFR BA 2 A_Refire("HoldAlt");
        Goto RealReady;
	}
}

class BBDragonFireBall : Actor
{
    Default{
        Projectile;
        Speed 40;
        Scale 2.0;
        Damage 3.0;

        DeathSound "weapons/nuke/explode";
    }

    States
    {
        Spawn:
            MANF AB 2;
            Loop;
        Death:
            MISL A 0{
                RadiusAttack(target,32,64);
                for (int i=0; i < 4; i++){
                    A_SpawnItemEx("NapalmFlame",0,0,0, random(-8,8),random(-8,8),0);
                }
            }
            MISL ABCD 2;
            Stop;
    }
}

// Will implement proper projectile soon, but it should be good for now
class BBDragonFlame : Actor{
    Default
	{
		Radius 16;
		Height 8;
		Scale 0.5;
		Speed 40;
		Damage 75;
		DeathSound "weapons/nuke/explode";
		Obituary "$SPOT_KILL_NAPALM";
		+RANDOMIZE
		+ROCKETTRAIL
		+ZDOOMTRANS
	}

	States
	{
		Spawn:
			NFRL A 0;
		Death:
			NFRL ACEGIK 2 bright{
				RadiusAttack(target,16,16);
			}
			NFRD ABCDEFGHIJKLMNO 2 bright RadiusAttack(target,15,32, "none", RADF_THRUSTLESS);
			Stop;
	}
}