class SpotMallet : BlueBastardWeapon
{
	mixin BBSpotWeapon;
	Default
	{
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		
		Tag "$SPOT_MALLET";
		//Weapon.WeaponScaleX 0.75;
		//Weapon.WeaponScaleY 0.8;

		Obituary "$SPOT_KILL_MALLET";
	}
	States
	{
	Deselect:
		MTCD ABCDE 3;
		MTCD E 1 A_Lower(24);
		Wait;
	Select:
		MTCD E 1 A_Lower(24);
		Wait;
	Ready:
		MTCD EDC 3;
		MTCD A 0 A_PlaySound("weapons/generic/draw");
		MTCD BA 3;
	RealReady:
		MALL A 1 A_WeaponReady;
		Loop;
	Fire:
		MALL BBCCDD 1 A_SetAngle(self.angle + 2, SPF_INTERPOLATE);
		MALL D 2;
		Goto Hold_Check;
	Hold_Check:
		MALL D 0{
			if (player.cmd.buttons & BT_ATTACK)
			{
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
				return ResolveState("Hold");
			} 
			else
			{
				return ResolveState("Swing");
			}
		}
	Hold:
		MALL D 1;
		Goto Hold_Check;
	Swing:
		MALL DEF 1 A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
		MALL G 0 A_Recoil(-4);
		MALL G 0;
		MALL G 1{
			int dmg = random(15,50);
			A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardPunchPuff", range: meleeRange + 20, meleesound: "weapons/mallet", misssound: "weapons/mallet/miss");
		}
		MALL HIJ 1 A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
		TNT1 A 10;
		MTCD EDCBA 3;
		Goto RealReady;
	}
}

class SpotChainsaw : BlueBastardWeapon
{
	mixin BBSpotWeapon;
	Default
	{
		
		+WEAPON.MELEEWEAPON
		Tag "$SPOT_CHAINSAW";

		Obituary "$SPOT_KILL_CHAINSAW";

		+INVENTORY.UNDROPPABLE
	}
	States
	{
		Deselect:
			SSWR ABCDE 2 A_StopSound(CHAN_6);
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SSWR EDC 2;
			SSWP A 0 A_PlaySound("weapons/chainsaw/pull", CHAN_AUTO);
			SSWP ABC 2;
			SSWP DDEEFF 1 {
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SSWP A 0 A_PlaySound("weapons/chainsaw/idle", CHAN_6, 1.0, true);
			SSWR BBAA 1 A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
		RealReady:
			SSAW AABBCCDD 1{
				A_WeaponReady();
				A_WeaponOffset(Random(-1,1),Random(-1,1) + 36);
			}
			Loop;
		Fire:
			SSWT A 1;
		RealFire:
			SSWP A 0 A_PlaySound("weapons/chainsaw/attack", CHAN_6, 1.0, true);
			SSWP A 0 A_Saw("","weapons/chainsaw",2,"BlueBastardBulletPuffSaw");
			SSWA AB 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
			}
			SSWA A 0 A_ReFire("RealFire");
			SSWT A 1;
			SSWP A 0 A_PlaySound("weapons/chainsaw/idle", CHAN_6, 1.0, true);
			Goto RealReady;
	}
}

class SpotKicky : CustomInventory
{
    States
    {
    Use:
		TNT1 A 0 {
			int kick_type = random(1,2);
			if (kick_type == 1){
				A_Overlay(-2,"Kicky",1);
			}
			else{
				A_Overlay(-2,"RoadHouse",1);
			}
		}
        TNT1 A 0 A_OverlayOffset(-2,0,16);
        Fail;
    Kicky:
        SKCK A 1 A_StartSound("weapons/kick/miss",CHAN_AUTO);
		SKCK BC 1;
        SKCK D 2 {
			int dmg = random(10,20);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 6;
			}
			A_CustomPunch(dmg, norandom:true, flags: 0, pufftype: "BlueBastardKickPuff", range: meleeRange + 20, meleesound: "weapons/kick", misssound: "");
		}
        SKCK EFGHA 2;
        Stop;
	RoadHouse:
		SRDH A 1 A_StartSound("weapons/kick/miss",CHAN_AUTO);
		SRDH B 1;
        SRDH C 2 {
			int dmg = random(10,20);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 6;
			}
			A_CustomPunch(dmg, norandom:true, flags: 0, pufftype: "BlueBastardKickPuff", range: meleeRange + 20, meleesound: "weapons/kick", misssound: "");
		}
        SRDH DEFGH 2;
        Stop;
    }
}