
class SpotRocketLauncher : RocketLauncher
{
		Default{
		Weapon.AmmoType "RocketAmmo";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 4;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.NOAUTOFIRE
		+INVENTORY.UNDROPPABLE

		Obituary "$SPOT_KILL_ROCKET";

		Tag "$SPOT_ROCKET";
	}
	States {
		Deselect:
			SMSR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SMSR EDC 2;
			SMSR A 0 A_PlaySound("weapons/missle/deploy");
			SMSR BA 2;
		RealReady:
			SMSL A 1 A_WeaponReady;
			Loop;
		Fire:
			SMSL A 0{
				A_FireProjectile("NapalmRocket", 1, true, -10, -10);
				A_FireProjectile("NapalmRocket", 1, true, -10, 10);
				A_FireProjectile("NapalmRocket", -1, true, 10, -10);
				A_FireProjectile("NapalmRocket", -1, true, 10, 10);
				A_Light(4);
				A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
			}
			SMSL BC 1{
				A_Light(2);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			}
			SMSL DDDDDDDDDDDD 1{
				A_Light0();
				A_WeaponOffset(Random(-4,4),Random(-4,4) + 36);
			}
			SMSL DDDDDDD 2{
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SMSL A 0 A_Light0();
			SMSL DEF 2;
			SMSL A 0{;
				A_ReFire();
			}
			goto RealReady;
	}
}

// not as rapid anymore :(
class NapalmRocket : Rocket
{
	Default{
		Scale 1;
		Speed 24;
		Damage 16;
		SeeSound "weapons/nuke";
		DeathSound "weapons/nuke/explode";
	}

		States
	{
		Spawn:
			MISL A 1;
			Loop;
		Death:
			MISL B 0{
				A_QuakeEx( 3, 3, 3, 20, 0, 500 );
			} 
			// Napalm
			MISL BBBB 0{
				A_SpawnItemEx("NapalmFlame",0,0,0, random(-16,16),random(-16,16),0);
			}
			MISL B 8 Bright A_Explode;
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
}

class NapalmFlame : Actor
{
	Default
	{
		Radius 16;
		Height 8;
		Scale 1.0;
		Speed 40;
		Damage 75;
		DeathSound "weapons/nuke/explode";
		Obituary "$SPOT_KILL_NAPALM";
		+RANDOMIZE
		+ROCKETTRAIL
		+ZDOOMTRANS
	}

	States
	{
		Spawn:
			NFRL A 0;
		Death:
			NFRL ABCDEFGHIJKL 2 bright{
				RadiusAttack(target,15,32);
			}
			NFRD ABCDEFGHIJKLMNO 2 bright RadiusAttack(target,15,32);
			Stop;
	}
}

