class SpotShotgun : BlueBastardWeapon
{
	mixin BBSpotWeapon;
	bool pumped;
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		
		Tag "$SPOT_KS23";

		Obituary "SPOT_KILL_KS23";

		+INVENTORY.UNDROPPABLE
	}
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		pumped = false;
	}
	States {
		Deselect:
			SSHR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 offset(0,32);
			TNT1 A 0 
			{
				if(!invoker.pumped) return resolvestate("SelectPump");
				return resolvestate(Null);
			}
			TNT1 A 0 A_PlaySound("weapons/generic/draw");
			SSHR EDCBA 2;
			goto ready;
		SelectPump:
			SSHT B 1 Offset(-10,42);
			SSHT B 1 Offset(9,41);
			SSHT B 1 Offset(5,37);
			SSHT B 1 Offset(2,34);
			TNT1 A 0 Offset(0,32);
			goto Pump+1;
		Ready:
			SSHT A 1 A_WeaponReady;
			wait;
		Fire:
			SSTF A 0
			{
				A_FireBullets(7, 4, 25, 5, "BlueBastardBulletPuff");
				A_Recoil(1);
				A_PlaySound("weapons/ks23/fire", CHAN_WEAPON);
				Invoker.Pumped = false;
				A_GunFlash();
				A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
			}
			SSTF CBAA 1{
				A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SSHT A 6 A_Weaponready(WRF_NOFIRE); //I think it would be neat for Spot to be able to switch the weapon in quick succession if needed.
		Pump:
			SSHT BCD 2;
			SSHT A 0
			{ 
				Invoker.Pumped = true;
				A_PlaySound("weapons/shotgun/pump");
			}
			SSHT EF 2;
			SSHT EDCBA 2;
			SSHT A 0 A_ReFire;
			goto Ready;
		Flash:
			SHTF A 1 Bright A_Light2;
			SHTF B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			goto Lightdone;
	}
}

class SpotShotgunClassic : BlueBastardWeapon
{
	mixin BBSpotWeapon;
	bool pumped;
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 2;
		Weapon.AmmoGive 8;
		
		Tag "$SPOT_SHTCLASSIC";

		Obituary "$SPOT_KILL_SHTCLASSIC";
		+INVENTORY.UNDROPPABLE
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		pumped = false;
	}
	States {
		Deselect:
			SH2R ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 offset(0,32);
			TNT1 A 0 
			{
				if(!invoker.pumped) return resolvestate("SelectPump");
				return resolvestate(Null);
			}
			TNT1 A 0 A_PlaySound("weapons/generic/draw");
			SH2R EDCBA 2;
			goto ready;
		SelectPump:
			SH2C B 1 Offset(-10,42);
			SH2C B 1 Offset(9,41);
			SH2C C 1 Offset(5,37);
			SH2C C 1 Offset(2,34);
			TNT1 A 0 Offset(0,32);
			goto Pump+2;
		Ready:
			SHT2 A 1 A_WeaponReady;
			Loop;
		Fire:
			SHT2 A 0
			{
				A_FireBullets(12, 6, 32, 5, "BlueBastardBulletPuff");
				A_Recoil(4);
				A_PlaySound("weapons/ks23/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 12, SPF_INTERPOLATE);
				Invoker.Pumped = false;
			}
			SHT2 BCAAAA 1{
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SHT2 AAAAAA 2{
				A_WeaponOffset(Random(-1,1),Random(-1,1) + 36);
			}
			SHT2 A 6 A_Weaponready(WRF_NOFIRE); //I think it would be neat for Spot to be able to switch the weapon in quick succession if needed.
		Pump:
			SH2C BCD 3;
			SSHT A 0 {
				A_PlaySound("weapons/shotgun/pump");
				Invoker.Pumped = true;
			}
			SH2C EF 3;
			SH2C EDCBA 2;
			SH2C A 0 A_ReFire;
			goto Ready;
		Flash:
			SH2F A 1 Bright A_Light2;
			SH2F B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
	}
}

class SpotDevastator : BlueBastardWeapon
{
	mixin BBSpotWeapon;
	Default{
		Weapon.AmmoType "BBSpotDevastatorShell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		
		Tag "$SPOT_DEV";
		Obituary "SPOT_KILL_DEV";

		+INVENTORY.UNDROPPABLE
	}
	States {
		Deselect:
			DVTR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			DVTR EDC 2;
			DVTR A 0 A_PlaySound("weapons/autoshotgun/deploy");
			DVTR BA 2;
		RealReady:
			DVST A 1 A_WeaponReady;
			Loop;
		Fire:
			DVST B 0
			{
				A_FireBullets(7, 4, 16, 7, "BlueBastardBulletPuff");
				A_Recoil(1);
				A_PlaySound("weapons/shotgun/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 4, SPF_INTERPOLATE);
			}
			DVST BC 1;
			DVST DE 2 A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			DVST A 4;
			goto RealReady;
		Flash:
			DVTF A 1 Bright A_Light2;
			DVTF B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
	}
}

